
# not_comorbidities:
#   - 'falls'
#   - 'pregnant'
#   - 'clinical'
#   - 'NOT IN ENUMERATIONS LIST'
#   - 'chicken pox'
#   - 'acid reflux'
#   - 'pregnancy'
#   - 'none'
#   - 'no chronic problems'
#   - 'smoker'
#   - 'ex-smoker'
#   - 'carbapenemase producing enterobacteriacea'
#   - 'glasses'
#   - 'cpe - carbapenemase-producing enterobacteriacea'
#   - 'vitamin d deficiency'
#   - 'back pain'
#   - 'gastric reflux'
#   - 'daily cl wearer'

ischaemic_heart_disease:
  - "ihd - ischaemic heart disease"
  - "ischaemic heart disease"
  - "ihd - ischaemic heart disease"
  - "chronic ischaemic heart disease"
  - "ischamic heart disease"
  - "chronic ischaemic heart disease (disorder)"
  - "chronic ischaemic heart disease"

hypertension:
  - "hypertension"
  - "htn - hypertension"
  - "essential hypertension"
  - "benign hypertension (disorder)"
  - "hypertension stage 1"
  - "benign hypertension"
  - "benign essential hypertension"
  - "ht: hypertension"

type2_diabetes:
  - "type 2 diabetes mellitus"
  - "diabetes mellitus type 2"
  - "t2dm - diabetes mellitus type 2"
  - "diabetes mellitus type 2 (disorder)"
  - "diabetes type 2 on insulin"
  - "type 2 diabetes mellitus controlled by diet"
  - "t2dm"
  - "insulin treated type 2 diabetes mellitus"
  - "diabetes type 2"
  - "type 2 diabetes mellitus well controlled"
  - "type 2 diabetes mellitus uncontrolled"
  - "type 2 diabetes mellitus with multiple complications"
  - "type 2 diabetes"
  - "type 2 diabetic on insulin"
  - "type 2 dm"

type1_diabetes:
  - "type 1 diabetes mellitus"
  - "diabetes mellitus type 1"
  - "insulin dependent diabetes mellitus type 1a"
  - "type 1 diabetes mellitus"
  - "diabetes type 1"
  - "diabetes mellitus type i"

myocardial_infarction:
  - "mi - myocardial infarction"
  - "myocardial infarction"
  - "acute myocardial infarction"
  - "acute non-st segment elevation myocardial infarction"
  - "stemi - st elevation myocardial infarction"
  - "acute stemi (st elevation myocardial infarction) of anterior wall"
  - "acute st segment elevation mi (myocardial infarction) due to left coronary artery occlusion"
  - "acute st segment elevation myocardial infarction"
  - "acute anterior myocardial infarction"

heart_failure:
  - "heart failure"
  - "heart failure with reduced ejection fraction"
  - "chf - congestive heart failure"
  - "congestive heart failure"
  - "hf - heart failure"
  - "heart failure with normal ejection fraction"
  - "acute congestive heart failure"
  - "acute heart failure"
  - "heart failure with mid range ejection fraction"
  - "hfref - heart failure with reduced ejection fraction"
  - "heart failure with preserved ejection fraction"

# hypercholesterolaemia:
#   - "hypercholesterolaemia"
#   - "hypercholesterolemia"
#   - "high cholesterol"
#   - "pure hypercholesterolaemia"
#   - "serum cholesterol raised"
#   - "raised cholesterol"
#   - "hypercholesterolemia (disorder)"

blood_cancer:
  - "lymphoma"
  - "angioimmunoblastic t-cell lymphoma"
  - "malignant lymphoma"
  - "chronic lymphocytic leukemia"
  - "b-cll - b-cell chronic lymphocytic leukemia"
  - "aml - acute myeloblastic leukemia"
  - "follicular non-hodgkin's lymphoma"
  - "aml - acute myeloid leukemia"
  - "dlbcl (diffuse large b-cell lymphoma) associated with chronic inflammation"
  - "high grade lymphoma"

# obesity:
#   - "obesity"
#   - "bmi 30+ - obesity"
#   - "overweight"
#   - "morbid obesity"
#   - "obesity (disorder)"
#   - "bmi 25-29 - overweight"
#   - "morbid obesity (disorder)"
#   - "body mass index 30+ - obesity"

copd:
  - "copd - chronic obstructive pulmonary disease"
  - "copd (chronic obstructive pulmonary disease) 3 monthly review"
  - "copd (chronic obstructive pulmonary disease) disturbs sleep"
  - "copd (chronic obstructive pulmonary disease) assessment test scale"
  - "clinical copd (chronic obstructive pulmonary disease) questionnaire total score"
  - "copd (chronic obstructive pulmonary disease) does not disturb sleep"
  - "copd (chronic obstructive pulmonary disease) patient unsuitable for pulmonary rehabilitation"

# dementia:
#   - "dementia"
#   - "senile dementia"
#   - "bpsd - behavioral and psychological symptoms of dementia"
#   - "alcoholic dementia"

anemia:
  - "anaemia"
  - "anemia"
  - "iron deficiency anaemia"
  - "ida - iron deficiency anemia"
  - "iron deficiency"
  - "iron deficiency anemia"
  - "ida - iron deficiency anaemia"
  - "microcytic anaemia"
  - "microcytic anemia"
  - "ida - iron deficiency anemia"
  - "deficiency anaemias"
  - "normocytic anemia"

renal_failure:
- "esrf - end stage renal failure"
- "end stage renal failure on dialysis"
- "end stage renal failure with renal transplant"
- "renal failure"
- "chronic renal failure"
- "acute renal failure"
- "chronic progressive renal failure (disorder)"
- "end stage chronic renal failure"


asthma:
- "asthma"
- "asthma (disorder)"
- "mild asthma"
- "childhood asthma"
- "brittle asthma"
- "acute asthma"
- "exercise-induced asthma"
- "h/o: asthma"
- "asthma attack"

cancer:
- "breast cancer"
- "cancer"
- "rectal cancer"
- "bladder cancer"
- "prostate cancer"
- "adenocarcinoma"
- "lung cancer"
- "cancer of prostate"
- "colorectal cancer"
- "ovarian cancer"
- "urothelial carcinoma"
- "ca - cancer of prostate"
- "pancreatic cancer"
- "malignant neoplasm"
- "adenocarcinoma of endometrium"
- "oesophageal cancer"
- "basal cell carcinoma"
- "peritoneal cancer"
- "malignant"
- "cancer of bowel"
- "scc - squamous cell carcinoma"
- "liver cancer"
- "malignant tumour of rectum"
- "renal cell carcinoma"
- "adenocarcinoma of sigmoid colon"
- "ca - bladder cancer"
- "ca - cancer of colon"
- "malignant tumour of oesophagus"
- "malignant tumour of breast"
- "cancer of colon"
- "colon cancer stage 4"
- "malignant tumour of urinary bladder"
- "gastric cancer"
- "ca - lung cancer"
- "squamous cell carcinoma"
- "bcc - basal cell carcinoma"
- "primary malignant neoplasm"
- "adenocarcinoma of prostate"
- "adenocarcinoma of lung"
- "endometrial carcinoma"
- "laryngeal cancer"
- "tcc - transitional cell carcinoma of bladder"
- "ca - cancer of pancreas"
- "malignant tumour of prostate"
- "cholangiocarcinoma"
- "malignant tumour of colon"
- "malignant tumour"
- "cancer of cervix"
- "malignant tumour of ovary"
- "anal carcinoma"
- "cin i - cervical intraepithelial neoplasia 1"
- "ultrasound scan surveillance of liver for hepatocellular carcinoma"
- "adenocarcinoma of rectum"
- "cancer metastatic to liver"
- "scc - squamous cell carcinoma of tongue"
- "carcinoma"
- "cin 2 - cervical intraepithelial neoplasia 2"
- "cancer of vulva"
- "cancer of endometrium"
- "ascending colon cancer"
- "neuroendocrine carcinoma"
- "cancer metastatic to lung"
- "primary vulval cancer"
- "malignant tumour of sigmoid colon"
- "metastasis to liver from adenocarcinoma"
- "rectosigmoid colon cancer"
- "grade 3 (stage pta) papillary urothelial/transitional cell carcinoma"
- "duodenal cancer"
- "ovarian cancer stage 4"
- "vin iii - vulval intraepithelial neoplasia grade iii"
- "scc - squamous cell carcinoma of lung"
- "adenocarcinoma of oesophagus"
- "primary squamous cell carcinoma of lower third of oesophagus"
- "intraductal carcinoma in situ of breast"
- "sigmoid colon cancer"
- "intraductal carcinoma"
- "local recurrence of malignant tumor of rectum"
- "primary adenocarcinoma of ascending colon"
- "ca - cancer of bowel"
- "secondary malignant neoplasm of liver and intrahepatic bile duct"
- "malignant neoplasm of lower third of oesophagus"
- "malignant tumour of large intestine"
- "carcinoma of prostate"
- "transitional cell carcinoma, micropapillary"
- "ca - pancreatic cancer"
- "squamous cell carcinoma of skin"
- "colon cancer stage 1"
- "papillary thyroid carcinoma"
- "hepatocellular carcinoma"
- "grade 2 (stage pta) papillary urothelial/transitional cell carcinoma"
- "renal cancer"
- "ca - carcinoma of breast"
- "scc - squamous cell carcinoma of skin"
- "ampullary carcinoma"
- "squamous cell carcinoma of vulva"
- "cin 3 - cervical intraepithelial neoplasia grade 3"
- "carcinoma of breast"
- "adenocarcinoma of rectosigmoid junction"
- "ductal carcinoma"
- "carcinoma of caecum"
- "papillary urothelial carcinoma"
- "primary adenocarcinoma of lower third of oesophagus due to barrett oesophagus"
- "cancer in situ of anal canal"
- "[m]transitional cell carcinoma nos"
- "malignant tumour of stomach"
- "scc - squamous cell carcinoma of buccal mucosa"
- "invasive ductal carcinoma of breast"
- "malignant neoplasm of endometrium of corpus uteri"
- "malignant phaeochromocytoma"
- "squamous cell carcinoma of lung"
- "cancer metastatic to left lung"
- "adenoid cystic carcinoma"
- "international federation of gynecology and obstetrics endometrial cancer stage i a"
- "cancer in situ"
- "cancer hospital treatment completed"
- "primary malignant neoplasm of prostate"
- "carcinoma of thyroid"
- "metastatic renal cell carcinoma"
- "carcinoma of colon, stage iv"
- "cancer - unknown origin"
- "descending colon cancer"
- "small cell ovarian carcinoma"
- "squamous cell carcinoma of anal margin"
- "cancer metastatic to rectum"
- "basal cell carcinoma of face"
- "adenocarcinoma, metastatic"
- "cancer metastatic to abdominal organs"
- "cancer in situ of rectum"
- "polypoid squamous cell carcinoma"
- "adenocarcinoma of cervix"
- "squamous cell carcinoma of tongue"
- "clear cell renal cell carcinoma"
- "cholangiocarcinoma of biliary tract"
- "carcinoma in situ of liver"
- "mucinous adenocarcinoma"
- "malignant neoplasm of urinary bladder"
- "squamous cell carcinoma of oropharynx"
- "ca - cancer of large bowel"
- "malignant tumour of urethra"
- "metastatic malignant neoplasm to liver"
- "carcinoma in situ of bladder"
- "prostate carcinoma"
- "squamous cell carcinoma - category"
- "ain - anal intraepithelial neoplasia"
- "malignant neoplasm of cervix uteri"
- "oesophageal adenocarcinoma in situ"
- "cancer metastatic to kidney"
- "malignant lymphoma"
- "carcinoma of bladder"
- "squamous non-small cell lung cancer"
- "smooth muscle tumor of uncertain malignant potential"
- "adrenal carcinoma"
- "thyroid cancer"
- "malignant ascites"
- "bcc - basal cell carcinoma of skin"
- "malignant tumour of pylorus"
- "basal cell carcinoma of nose"
- "rectal carcinoma"
- "tcc - transitional cell carcinoma"
- "severe dyskaryosis on cervical smear cannot exclude invasive carcinoma"
- "ca - breast cancer"
- "bowel cancer"
- "cancer of skin"
- "carcinoma, metastatic"
- "peritoneal carcinomatosis"
- "malignant melanoma of skin"
- "appendiceal cancer"
- "cancer in situ of duodenum"
- "cervical intraepithelial neoplasia grade 1"
- "ca - cancer of unknown origin"
- "primary adenocarcinoma of oesophagogastric junction"
- "malignant neoplasm of breast"
- "malignant neoplasm of colon"
- "malignant neoplasm of middle third of oesophagus"
- "international federation of gynaecology and obstetrics (figo) stage for endometrial\ carcinoma"
- "adenocarcinoma of appendix"
- "malignant tumour of cervix"
- "metastatic cancer"
- "squamous cell carcinoma of cervix"
- "malignant melanoma"
- "invasive cervical cancer"
- "adenocarcinoma of bladder"
- "adenocarcinoma of anorectum"
- "malignant neoplasm of body of pancreas"
- "ca - squamous cell carcinoma of vulva"
- "malignant tumour of larynx"
- "malignant neoplasm of body of stomach"
- "cancer of stomach"
- "cin - cervical intraepithelial neoplasia"
- "cancer of anal canal"
- "squamous cell carcinoma of larynx"
- "late gastric cancer"
- "adenocarcinoma of lung, stage iv"
- "cervical cancer"
- "adenocarcinoma of duodenum"
- "malignant tumour of intestine"
- "hepatic flexure colon cancer"
- "carcinoma of anal canal"
- "pelvic sidewall involved by direct extension of malignant neoplasm"
- "primary cholangiocarcinoma of extrahepatic bile duct"
- "squamous cell carcinoma of scalp"
- "metastatic papillary thyroid carcinoma"
- "intrahepatic bile duct carcinoma"
- "transitional cell carcinoma of bladder"
- "malignant neoplasm of cervix"
- "[m]squamous cell carcinoma in situ nos"
- "anal intraepithelial neoplasia (ain iii)"
- "ca - cancer of tongue"
- "renal carcinoma, collecting duct type"
- "malignant neoplasm of bladder neck"
- "adenocarcinoma of left lung"
- "primary squamous cell carcinoma of lower lobe of left lung"
- "adenocarcinoma - intestinal type"
- "primary adenocarcinoma of descending colon"
- "colon cancer, stage 3"
- "ductal carcinoma in situ (breast)"
- "ca - cancer of ovary"
- "vulval intraepithelial neoplasia (vin)"
- "mouth cancer"
- "breast cancer remission"
- "adenocarcinoma of stomach"
- "scc - squamous cell carcinoma of anal margin"
- "secondary malignant neoplasm of liver"
- "paget disease vulvar cancer"
- "adenocarcinoma of esophagus"
